import { z } from "zod";

/**
 * Maximum message length supported by the initial public-chat MVP.
 *
 * Runtime configuration in Agent Core may apply a stricter limit, but it
 * must never accept a value above this public contract without versioning
 * the API.
 */
export const PUBLIC_CHAT_MAX_MESSAGE_LENGTH = 4_000;

/**
 * Public identifier generated by Agent Core and persisted by the browser.
 *
 * This is deliberately not an OpenClaw session key. Values such as
 * `agent:real-estate-agent:...` are rejected because colons are not allowed.
 */
export const publicChatSessionIdSchema = z
  .string()
  .trim()
  .min(8, "sessionId must contain at least 8 characters")
  .max(128, "sessionId must contain at most 128 characters")
  .regex(
    /^[A-Za-z0-9_-]+$/,
    "sessionId may only contain letters, numbers, underscores and hyphens"
  );

export const publicChatRequestSchema = z
  .object({
    sessionId: publicChatSessionIdSchema.optional(),
    message: z
      .string()
      .trim()
      .min(1, "message is required")
      .max(
        PUBLIC_CHAT_MAX_MESSAGE_LENGTH,
        `message must contain at most ${PUBLIC_CHAT_MAX_MESSAGE_LENGTH} characters`
      )
  })
  .strict();

export const publicChatTextPayloadSchema = z
  .object({
    type: z.literal("text"),
    text: z.string().trim().min(1)
  })
  .strict();

export const publicChatMediaPayloadSchema = z
  .object({
    type: z.literal("media"),
    url: z
      .string()
      .url()
      .regex(/^https?:\/\//i, "media URL must use http or https")
  })
  .strict();

export const publicChatPayloadSchema = z.discriminatedUnion("type", [
  publicChatTextPayloadSchema,
  publicChatMediaPayloadSchema
]);

export const publicChatDataSchema = z
  .object({
    sessionId: publicChatSessionIdSchema,
    message: z.string(),
    payloads: z.array(publicChatPayloadSchema)
  })
  .strict();

export const publicChatResponseSchema = z
  .object({
    success: z.literal(true),
    data: publicChatDataSchema
  })
  .strict();

export const publicHealthResponseSchema = z
  .object({
    success: z.literal(true),
    data: z
      .object({
        status: z.literal("ok")
      })
      .strict()
  })
  .strict();

export type PublicChatSessionId = z.infer<
  typeof publicChatSessionIdSchema
>;
export type PublicChatRequest = z.infer<typeof publicChatRequestSchema>;
export type PublicChatTextPayload = z.infer<
  typeof publicChatTextPayloadSchema
>;
export type PublicChatMediaPayload = z.infer<
  typeof publicChatMediaPayloadSchema
>;
export type PublicChatPayload = z.infer<typeof publicChatPayloadSchema>;
export type PublicChatData = z.infer<typeof publicChatDataSchema>;
export type PublicChatResponse = z.infer<
  typeof publicChatResponseSchema
>;
export type PublicHealthResponse = z.infer<
  typeof publicHealthResponseSchema
>;
